[package]
name = "voipc-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
